### ISSUE TITLE
Support new standalone mode

### ISSUE THREAD

**Issue by Ghabry** [carlsonsantana/convert_rpggame_to_android#4]
There will be soon a better standalone mode for EasyRPG Player.

The changes are minimal:

Instead of ``assets/game`` the game folder must be a zip archive with Deflate compression called ``assets/game.zip``. I wanted to support both but the APK API does not report directory when listing directory content, so is unusable for us.

The ZIP can have one of two structures:

- The game content directly in the root, e.g. ``/RPG_RT.ldb``, ``/Map0001.lmu``, etc.
- A single folder containing the game, e.g. ``TestGame/RPG_RT.ldb``, ``TestGame/Map0001.lmu``

The second case will only work when there is nothing else except the folder in the ZIP root.

**Comment by carlsonsantana** [comment]
@Ghabry thank you for the advice, I update the project to support this change.
